# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "http://terremotocentroitalia.info"

#baseurl: "https://github.com/emergenzeha/terremotocentro"
url: "http://terremotocentroitalia.info"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Terremoto Centro Italia

# Short description of your site
description: Un progetto per informare sugli eventi sismici che hanno colpito il Centro Italia nel 2016.

# --- Navigation bar options --- #
# List of links in the navigation bar
navbar-links:
  Segnala: "segnala/"
  Richieste:
    - Fabbisogni: "fabbisogni/"
    - Cerco Lavoro: "cerco_lavoro/"
  Offerte:
    - Risorse: "risorse-disponibili/"
    - Alloggi: "alloggi/"
    - Offro Lavoro: "offro_lavoro/"
    - Ospitalità animali: "ospitalita_animali/"
  Raccolte:
    - Raccolte Fondi: "fondi/"
    - Acquisti Solidali: "acquistisolidali/"
  Aggiornamenti:
    - News: "news/"
    - Eventi: "eventi/"
    - Blog: "post/"
    - Storie: "storie/"
    - Vittime: "vittime/"
    - Bufale: "bufale/"
  Utilità:
    - Mappe: "mappe/"
    - Dashboard: "dashboard/"
    - Opendata: "opendata/"
    - Link e contatti utili: "link_utili/"
  Il Progetto:
   - About: "about/"
   - Contribuisci: 'https://github.com/emergenzeHack/terremotocentro/wiki" target="_blank'
   - Press: "press/"
   - Canali di Comunicazione: "canali/"
  Cerca: "search/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/noun_8681.png

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: TerremotoCentroItalia
  #email: "youremail@domain.com"
  facebook: groups/1758670357733881/  # eg. daattali
  github: emergenzeHack/terremotocentro    # eg. daattali
  twitter: terremotocentro   # eg. daattali
  linkedin:   # eg. daattali
  xing:       # eg. daattali
  stackoverflow:   # eg. "3943160/daattali"
  instagram: terremotocentro # eg. daattali
  youtube: yourlink # eg. user/daattali or channel/daattali
  rss: https://emergenzehack.github.io/terremotocentro/feed.xml
  telegram: https://telegram.me/terremotocentroitalia
  medium: https://medium.com/@terremotocentroitalia
  archiveorg: https://archive.org/details/@terremotocentroita
  messenger: messenger

# Select which links to show in the footer
footer-links-active:
  androidapp: true
  rss: true
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  instagram: true
  youtube: false
  telegram: true
  medium: true
  archiveorg: true
  messenger: true

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "terremotocentroitalia"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-47474515-3"

jekyll-crosseverything_to_medium:
  enabled: false
  useraccount: 'https://medium.com/terremotocentroitalia'

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Rome"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

jekyll-mentions:
  base_url: https://twitter.com

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

include:
  - _data

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - vendor
  - .gitlab-ci.yml

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
    - /scripts
    - /external
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

collections:
  storie:
    output: true

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: issuesjson
    template: issue
    name: number
    dir: issues

gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-tidy

jekyll_tidy:
  exclude: []
  compress_html: true

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
